planner_node:
  ros__parameters:
    kp: 0.065
    ki: 0.054
    kd: 0.024
    k: 1.0

    # ok tune (with kalmann filter) ----vv-----
    # kp: 0.045
    # ki: 0.036
    # kd: 0.035
    # k: 1.0

    # initial tune (slow) 
    # kp: 0.011
    # ki: 0.010
    # kd: 0.025
    # k: 1.0

    # damped, but steady state error 
    # kp: 0.035
    # ki: 0.008
    # kd: 0.015
    # k: 1.0
