services:
  stewart:
    build: &stewart_build
      context: ..
      dockerfile: docker/stewart/stewart.Dockerfile
      cache_from:
        - "stewart_image:${TAG}"
        - "stewart_image:main"
    image: "stewart_image:${TAG}"
    profiles:
      - deploy
    command: /bin/bash -c "ros2 launch bringup_stewart stewart.launch.py"
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/i2c-1

  stewart_dev:
    build: *stewart_build
    image: "stewart_image:dev_${TAG}"
    command: tail -F anything
    profiles:
      - develop
    volumes:
      - ${MONO_DIR}/src/stewart:/root/ament_ws/src
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/i2c-1
