services:
  foxglove:
    build:
      context: ..
      dockerfile: docker/vis_tools/foxglove.Dockerfile
      cache_from:
        - "foxglove:${TAG}"
        - "foxglove:main"
    image: "foxglove:${TAG}"
    platform: linux/arm64/v8
    profiles: [deploy, develop]
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=${FOXGLOVE_BRIDGE_PORT:?}"]
    ports:
      - "${FOXGLOVE_BRIDGE_PORT:?}:${FOXGLOVE_BRIDGE_PORT:?}"
