camera_driver_node:
  ros__parameters:
    debug: false

    frames_per_second: 30
    compute_homography: false

    checkerboard_nx: 9
    checkerboard_ny: 9
    checkerboard_segment_length: 0.02235
